site_name: SigEscola.docs
repo_url: https://github.com/prefeiturasp/SME-PTRF-Docs
copyright: Prefeitura Municipal de São Paulo

nav:
    - Início: index.md
    - O PTRF: ptrf.md
    - Termos e Conceitos: termos_conceitos.md
    - Funcionalidades:
          - 'UE':
                - 'Despesas da Escola': funcionalidades/ue/Despesas da Escola.md
          - 'DRE':
                - 'Funcionalidade A': funcionalidades/dre/funcionalidade_a.md
          - 'SME':
            - 'Parametrizações':
                - 'Associações': funcionalidades/sme/Associações.md
          - 'Geral':
                - 'Gestão de Usuários': funcionalidades/Geral/Gestão de Usuários.md
    - Documentação:
          - 'Sobre a documentação': sigescola_docs/docs_project.md
          - 'Exemplos de uso': sigescola_docs/mkdocs_exemplos_uso.md
          - 'Como colaborar': sigescola_docs/como_colaborar_docs.md
    - O projeto:
        - 'Visão geral': projeto/visao_geral_projeto.md
        - 'Guia de contribuição': projeto/guia_contribuicao.md
        - 'Acordo de trabalho': vazia.md
    - Informações Técnicas:
        - 'API': vazia.md
        - 'Release Notes': projeto/release_notes.md
        - Hotfixes:
            - 'Back': projeto/hotfixes_back.md
            - 'Front': projeto/hotfixes_front.md


extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/prefeiturasp/SME-PTRF
    group_test:
        test_macro: Teste de macro. Esse texto veio de uma macro.

theme:
    name: material
    features:
      - navigation.sections
      - navigation.expand
      - navigation.top
      - navigation.footer
    palette:

      # Palette toggle for light mode
       - scheme: default
         primary: teal
         toggle:
           icon: material/weather-night
           name: Modo Escuro

      # Palette toggle for dark mode
       - scheme: slate
         primary: teal
         toggle:
           icon: material/brightness-7
           name: Modo Claro
    language: pt-BR

extra_css:
  - stylesheets/extra.css

plugins:
    - macros
    - search

markdown_extensions:
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tasklist
    - pymdownx.tilde
    - pymdownx.caret
    - pymdownx.mark
    - admonition
